[project]
name = "fastapi-pipeline"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "fastapi[standard]>=0.114.2",
    "requests>=2.32.3",
    "uvicorn>=0.30.6",
]
